// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/notice/notice.proto

package notice

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NoticeService service

func NewNoticeServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NoticeService service

type NoticeService interface {
	Send(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*SendResponse, error)
}

type noticeService struct {
	c    client.Client
	name string
}

func NewNoticeService(name string, c client.Client) NoticeService {
	return &noticeService{
		c:    c,
		name: name,
	}
}

func (c *noticeService) Send(ctx context.Context, in *SendRequest, opts ...client.CallOption) (*SendResponse, error) {
	req := c.c.NewRequest(c.name, "NoticeService.Send", in)
	out := new(SendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NoticeService service

type NoticeServiceHandler interface {
	Send(context.Context, *SendRequest, *SendResponse) error
}

func RegisterNoticeServiceHandler(s server.Server, hdlr NoticeServiceHandler, opts ...server.HandlerOption) error {
	type noticeService interface {
		Send(ctx context.Context, in *SendRequest, out *SendResponse) error
	}
	type NoticeService struct {
		noticeService
	}
	h := &noticeServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&NoticeService{h}, opts...))
}

type noticeServiceHandler struct {
	NoticeServiceHandler
}

func (h *noticeServiceHandler) Send(ctx context.Context, in *SendRequest, out *SendResponse) error {
	return h.NoticeServiceHandler.Send(ctx, in, out)
}
